### ISSUE TITLE
Fly False Flag

### ISSUE THREAD

**Issue by coolpvpv** [funkemunky/Iris-Issues#85] opened 2019-03-29 22:47 UTC
Version Information
Iris Anticheat Version 1.7.9
Atlas Version 1.1.3.5
Bukkit/Spigot Version 1.7.10

Are you using the ViaVersion plugin
No

How to re-create
Steps:
1) i got on a horse and got off 

Video: https://streamable.com/xtd5v

**Comment by FozzieHi** [comment] 2019-03-30 08:49
Can you try and use the latest version of Iris? I cannot reproduce this.

**Comment by FozzieHi** [comment] 2019-03-30 08:51
This is fixed in the next update - thanks for reporting it.

**Closed by FozzieHi** 2019-03-30 08:51 UTC
