### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by MineFriend** [funkemunky/Iris-Issues#4] opened 2019-01-25 01:00 UTC
**Describe the bug**

**Version Information**
- Iris Anticheat Version 1.5.1
- Atlas Version 1.0.6
- Bukkit/Spigot Version 1.8.8

funke when one exceeds the limit of checks (like 34 times in more than 100 therefore 134 times) iris performs 34 times the command : http://prntscr.com/mbtks8

**Comment by MineFriend** [comment] 2019-01-25 01:38
another bug: https://youtu.be/6q4Xk7skbFA

**Comment by MineFriend** [comment] 2019-01-25 04:19
another bug: https://pastebin.com/YE4c88bA

**Comment by funkemunky** [comment] 2019-01-25 16:54
The first bug report you made, I will go ahead and fixed. 

The first "another bug" you posted is not a bug. Just because the name of the check isn't the same as the cheat does not mean that it's a bug.

The second "another bug" you posted is a known error that will be fixed in the next update released.

Thank you for the reports. Although, I do suggest you create separate issues for each bug so its more organized. Thank you.

**Comment by MineFriend** [comment] 2019-01-25 18:39
ok

**Comment by funkemunky** [comment] 2019-01-25 21:59
All has been fixed for the next update. Thanks for the report.

**Closed by funkemunky** 2019-01-25 21:59 UTC
