### ISSUE TITLE
InventoryMove, Fly (Type B) and NoSlowdown false flags

### ISSUE THREAD

**Issue by PiiSaba** [funkemunky/Iris-Issues#80] opened 2019-03-29 18:22 UTC
**Describe the bug**
InventoryMove: Immediately after entering /rl on chat, then click your inventory.
Fly (Type B): Place the block directly below the player with jumping.
NoSlowdown: Press "W" and "A", your sprint key while eating something.

**Version Information**
- Iris Anticheat Version: 1.8.0
- Atlas Version: 1.1.4
- Bukkit/Spigot Version: 1.8.8

**Are you using the ViaVersion plugin?**
No

**Server Logs**
The video shows.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
oops. I said on "Describe the bug".

**Screenshots/Video**
https://www.youtube.com/watch?v=0Thp2IKG34Y&feature=youtu.be

**Additional context**
no

**Comment by FozzieHi** [comment] 2019-03-30 09:10
I cannot reproduce the InventoryMove flag, the Fly Type B is fixed in the next update, I also cannot reproduce the NoSlowdown false flag.

**Comment by PiiSaba** [comment] 2019-03-30 09:34
I see.
NoSlowdown: Press "W" and "A" at the same time while eating. You will get flag.
InventoryClick: Click your inventory immediately after typing. /rl. You will get flag.

**Comment by FozzieHi** [comment] 2019-03-30 12:08
I have fixed NoSlowdown for the next update, I still cannot reproduce InventoryWalk but if it is only 1 violation on /reload it shouldn't really be an issue.

**Closed by FozzieHi** 2019-03-30 12:08 UTC
